<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\SpeechToSpeech.Core\SpeechToSpeech.Core.csproj" />
    <ProjectReference Include="..\..\src\SpeechToSpeech.Vad\SpeechToSpeech.Vad.csproj" />
    <ProjectReference Include="..\..\src\SpeechToSpeech.Stt\SpeechToSpeech.Stt.csproj" />
    <ProjectReference Include="..\..\src\SpeechToSpeech.Llm\SpeechToSpeech.Llm.csproj" />
    <ProjectReference Include="..\..\src\SpeechToSpeech.Tts\SpeechToSpeech.Tts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="NAudio" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
